book_repo: pivotal-cf/docs-book-wavefront-nozzle
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: "master"

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-wavefront-nozzle
    at_path: docs-content
    ref: "4.x"
  directory: wavefront-nozzle/4-x
  subnav_template: wavefront-nozzle_subnav.erb

  product_info:
    use_local_header: true
    latest_stable_version: 4.x
    changelog_href: https://docs-pcf-staging.sc2-04-pcf1-apps.oc.vmware.com/wavefront-nozzle/4-x/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: VMware Tanzu Observability by Wavefront Nozzle
    search_placeholder: VMware Tanzu Observability by Wavefront Nozzle 4.x
    url_prefix: /wavefront-nozzle/4-x
    local_product_version: "4.x"
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/wavefront-nozzle/3-x
        display_name: v3.x
      - url_prefix: http://docs.pivotal.io/wavefront-nozzle/2-x
        display_name: v2.x
